#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "json"
require "open3"
require "rouge"
require "yaml"

ROOT = File.expand_path("..", __dir__)
DATA_DIR = File.join(ROOT, "_data")
CSS_DIR = File.join(ROOT, "assets", "css")
COMMUNITY_DIR = File.join(ROOT, "_community_themes")
PYGMENTS_SCRIPT = <<~PYTHON
  import json
  import pygments
  from pygments.formatters import HtmlFormatter
  from pygments.styles import get_all_styles

  styles = []

  for name in sorted(get_all_styles()):
      formatter = HtmlFormatter(style=name)
      css = "\\n".join(
          line for line in formatter.get_style_defs(".highlight").splitlines()
          if line.startswith(".highlight")
      )
      styles.append({"name": name, "css": css})

  print(json.dumps({"version": pygments.__version__, "styles": styles}))
PYTHON

def css_scope(theme_name)
  escaped = theme_name.gsub("\\", "\\\\\\").gsub('"', '\\"')
  %(body[data-theme="#{escaped}"] .highlight)
end

def first_hex_after(css, property)
  css[/#{property}:\s*(#[0-9a-fA-F]{3,8})/, 1]
end

def base_rule(css, scope)
  css[/#{Regexp.escape(scope)}(?:,\s*#{Regexp.escape(scope)} \.w)?\s*\{(?<rule>.*?)\}/m, :rule] || ""
end

def scoped_css(css, name)
  css.gsub(/(?<![-\w])\.highlight(?![-\w])/, css_scope(name))
end

def relative_luminance(hex)
  normalized = hex.delete_prefix("#")
  normalized = normalized.chars.map { |char| char * 2 }.join if [3, 4].include?(normalized.length)
  normalized = normalized[0, 6]

  channels = normalized.scan(/../).map { |part| part.to_i(16) / 255.0 }
  linear = channels.map do |channel|
    channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055)**2.4
  end

  (0.2126 * linear[0]) + (0.7152 * linear[1]) + (0.0722 * linear[2])
end

def metadata_from_css(name, css, source)
  scope = css_scope(name)
  base = base_rule(css, scope)
  foreground = first_hex_after(base, "color") || first_hex_after(css[/#{Regexp.escape(scope)} \.n\s*\{(?<rule>.*?)\}/m, :rule].to_s, "color") || "#111111"
  background = first_hex_after(base, "background(?:-color)?") || first_hex_after(css[/#{Regexp.escape(scope)} pre\s*\{(?<rule>.*?)\}/m, :rule].to_s, "background(?:-color)?") || "#ffffff"

  {
    "name" => name,
    "foreground" => foreground,
    "background" => background,
    "mode" => relative_luminance(background) < 0.45 ? "dark" : "light",
    "source" => source,
    "css" => css
  }
end

def rouge_theme_metadata(name)
  scope = css_scope(name)
  css = Rouge::Theme.find(name).render(scope: scope)
  metadata_from_css(name, css, "rouge")
end

def ruby_llm_docs_theme_metadata
  [
    ["rubyllm.docs.light", "gruvbox.light", "#f2e9e3"],
    ["rubyllm.docs.dark", "gruvbox.dark", "#201a1d"]
  ].map do |name, rouge_name, background|
    scope = css_scope(name)
    css = Rouge::Theme.find(rouge_name).render(scope: scope)
    css << "\n#{scope}, #{scope} .w {\n  background-color: #{background};\n}\n"

    metadata_from_css(name, css, "rubyllm").merge(
      "background" => background,
      "mode" => relative_luminance(background) < 0.45 ? "dark" : "light"
    )
  end
end

def pygments_theme_metadata
  stdout, stderr, status = Open3.capture3("python3", "-c", PYGMENTS_SCRIPT)

  unless status.success?
    warn "Skipping Pygments styles: #{stderr.strip}"
    return []
  end

  JSON.parse(stdout).fetch("styles").map do |style|
    name = "pygments.#{style.fetch("name")}"
      css = style.fetch("css").gsub(".highlight", css_scope(name))
    metadata_from_css(name, css, "pygments")
  end
rescue Errno::ENOENT, JSON::ParserError, KeyError => error
  warn "Skipping Pygments styles: #{error.message}"
  []
end

def community_theme_metadata
  Dir.glob(File.join(COMMUNITY_DIR, "*.css")).sort.map do |path|
    short_name = File.basename(path, ".css")
    name = "community.#{short_name}"
    css = File.read(path)
    metadata_from_css(name, scoped_css(css, name), "community")
  end
rescue Errno::ENOENT => error
  warn "Skipping community styles: #{error.message}"
  []
end

def write_rouge_data(themes)
  payload = {
    "rouge_version" => Gem.loaded_specs.fetch("rouge").version.to_s,
    "default_theme" => themes.find { |theme| theme["name"] == "github" }.fetch("name"),
    "theme_count" => themes.length,
    "themes" => themes.map do |theme|
      theme.reject { |key, _value| key == "css" }
    end
  }

  File.write(File.join(DATA_DIR, "rouge.yml"), <<~YAML)
    # Generated by script/generate_rouge_assets.rb. Do not edit by hand.
    #{payload.to_yaml.sub(/\A---\n/, "")}
  YAML
end

def write_theme_css(themes)
  css = +"/* Generated by script/generate_rouge_assets.rb. Do not edit by hand. */\n\n"

  themes.each do |theme|
    css << "body[data-theme=\"#{theme.fetch("name")}\"] {\n"
    css << "  --active-code-bg: #{theme.fetch("background")};\n"
    css << "  --active-code-fg: #{theme.fetch("foreground")};\n"
    css << "}\n\n"
    css << theme.fetch("css")
    css << "\n\n"
  end

  File.write(File.join(CSS_DIR, "rouge-themes.css"), css)
end

FileUtils.mkdir_p(DATA_DIR)
FileUtils.mkdir_p(CSS_DIR)

themes = Rouge::Theme.registry.keys.sort.map { |name| rouge_theme_metadata(name) }
themes.concat(ruby_llm_docs_theme_metadata)
themes.concat(pygments_theme_metadata)
themes.concat(community_theme_metadata)

write_rouge_data(themes)
write_theme_css(themes)

puts "Generated #{themes.length} themes."
